[package]
name = "e2e-keel"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]
name = "e2e_keel"

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
spin-sdk = "3"
tracing = "0.1"
urlencoding = "2"
