spin_manifest_version = 2

[application]
name = "keel-e2e"
version = "0.1.0"
description = "E2E app exercising Keel infra components via Spin SQLite"


[[trigger.http]]
route = "/..."
component = "e2e-api"

[component.e2e-api]
source = "../../target/wasm32-wasip2/release/e2e_keel.wasm"
allowed_outbound_hosts = []

# Grant SQLite capability with a default database binding
sqlite_databases = ["default"]
environment = { SPIN_SQLITE_DB_default = "sqlite:dev.db" }

# spin-test integration is paused pending alignment on WIT versions
# [component.e2e-api.tool.spin-test]
# source = "tests-rs/target/wasm32-wasip1/release/wasm_test.wasm"
# build = "(cargo component --version >/dev/null 2>&1 || cargo install cargo-component --locked) && cargo component build --release --target-dir=target"
# workdir = "tests-rs"

[component.e2e-api.build]
command = "cargo build --target wasm32-wasip2 --release"
watch = ["src/**/*.rs", "Cargo.toml"]
