#:schema https://schemas.spinframework.dev/spin/manifest-v2/latest.json

spin_manifest_version = 2

[application]
name = "feasability-spin-sanity"
version = "0.1.0"
authors = ["Marc Love <marclove@users.noreply.github.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "feasability-spin-sanity"

[component.feasability-spin-sanity]
source = "target/wasm32-wasip1/release/feasability_spin_sanity.wasm"
allowed_outbound_hosts = []
[component.feasability-spin-sanity.build]
command = "cargo build --target wasm32-wasip1 --release"
watch = ["src/**/*.rs", "Cargo.toml"]
